import {
  Product,
  Company,
  Farmer,
  DeliveryZone,
  SubscriptionPlan,
} from "@/types";

export const companies: Company[] = [
  {
    id: 1,
    name: "Seventh Generation",
    description:
      "Household products with plant-based ingredients and recycled packaging",
    location: "USA",
    ecoFocus: "Plant-based cleaning products with recycled packaging",
    image:
      "https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=400&h=300&fit=crop",
    certifications: ["EPA Safer Choice", "USDA Biobased", "Leaping Bunny"],
    foundedYear: 1988,
    productCount: 45,
  },
  {
    id: 2,
    name: "Mamaearth",
    description: "Natural, toxin-free skincare and baby care products",
    location: "India",
    ecoFocus: "Natural and toxin-free personal care products",
    image:
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=300&fit=crop",
    certifications: ["Made Safe", "Dermatologically Tested", "FDA Approved"],
    foundedYear: 2016,
    productCount: 120,
  },
  {
    id: 3,
    name: "Patagonia",
    description:
      "Sustainable outdoor clothing using recycled materials and fair trade practices",
    location: "USA",
    ecoFocus: "Sustainable outdoor apparel with recycled materials",
    image:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop",
    certifications: ["Fair Trade", "Organic Cotton", "Recycled Materials"],
    foundedYear: 1973,
    productCount: 200,
  },
  {
    id: 4,
    name: "Lush",
    description:
      "Handmade cosmetics with minimal packaging and ethical sourcing",
    location: "UK",
    ecoFocus: "Handmade cosmetics with minimal packaging",
    image:
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400&h=300&fit=crop",
    certifications: ["Cruelty Free", "Vegetarian Society", "Ethical Trading"],
    foundedYear: 1995,
    productCount: 300,
  },
  {
    id: 5,
    name: "Beco",
    description: "Biodegradable home cleaning and personal hygiene products",
    location: "India",
    ecoFocus: "Biodegradable cleaning and hygiene products",
    image:
      "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop",
    certifications: ["Biodegradable", "Plastic Free", "Chemical Free"],
    foundedYear: 2019,
    productCount: 35,
  },
  {
    id: 6,
    name: "FabIndia",
    description: "Organic cotton, handloom, and sustainable traditional wear",
    location: "India",
    ecoFocus: "Organic cotton and handloom sustainable fashion",
    image:
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop",
    certifications: ["Organic Cotton", "Fair Trade", "Handloom"],
    foundedYear: 1960,
    productCount: 500,
  },
  {
    id: 7,
    name: "The Honest Company",
    description:
      "Baby, personal care, and cleaning products made from natural ingredients",
    location: "USA",
    ecoFocus: "Natural ingredients and plant-based formulations",
    image:
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=300&fit=crop",
    certifications: ["USDA Biobased", "Cruelty Free", "Dermatologist Tested"],
    foundedYear: 2011,
    productCount: 75,
  },
  {
    id: 8,
    name: "Ecover",
    description: "Eco-friendly cleaning products with plant-based ingredients",
    location: "Belgium",
    ecoFocus: "Plant-based cleaning solutions and biodegradable formulas",
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    certifications: ["EU Ecolabel", "Cradle to Cradle", "Leaping Bunny"],
    foundedYear: 1980,
    productCount: 60,
  },
  {
    id: 9,
    name: "Allbirds",
    description:
      "Shoes and apparel made from natural materials like merino wool and eucalyptus",
    location: "New Zealand / USA",
    ecoFocus: "Natural materials and carbon neutral production",
    image:
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=300&fit=crop",
    certifications: ["Certified B Corp", "Carbon Neutral", "ZQ Merino"],
    foundedYear: 2016,
    productCount: 85,
  },
  {
    id: 10,
    name: "The Body Shop",
    description: "Cruelty-free, ethically sourced ingredients, refill stations",
    location: "UK",
    ecoFocus: "Ethical sourcing and community fair trade",
    image:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop",
    certifications: ["Cruelty Free", "Fair Trade", "Vegetarian Society"],
    foundedYear: 1976,
    productCount: 400,
  },
];

export const products: Product[] = [
  // Fresh Produce
  {
    id: 1,
    name: "Organic Red Apples",
    company: "Green Valley Farm",
    price: 399,
    unit: "per kg",
    image: "🍎",
    category: "Fresh Fruits",
    rating: 4.8,
    reviews: 124,
    description: "Crisp, sweet organic apples grown without pesticides",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["USDA Organic", "Pesticide Free"],
  },
  {
    id: 2,
    name: "Fresh Organic Spinach",
    company: "Sunshine Organics",
    price: 279,
    unit: "per bunch",
    image: "🥬",
    category: "Vegetables",
    rating: 4.9,
    reviews: 89,
    description: "Baby spinach leaves, perfect for salads and smoothies",
    inStock: true,
    deliveryTime: "Next day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Organic", "Pesticide Free"],
  },
  {
    id: 3,
    name: "Farm Fresh Milk",
    company: "Happy Hen Farm",
    price: 65,
    unit: "per liter",
    image: "🥛",
    category: "Dairy & Eggs",
    rating: 4.7,
    reviews: 156,
    description: "Fresh, pure milk from grass-fed cows",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Organic", "Grass Fed"],
  },
  {
    id: 4,
    name: "Organic Carrots",
    company: "Heritage Gardens",
    price: 220,
    unit: "per kg",
    image: "🥕",
    category: "Vegetables",
    rating: 4.6,
    reviews: 203,
    description: "Sweet, crunchy organic carrots perfect for cooking",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Organic", "Locally Grown"],
  },

  // Seventh Generation Products
  {
    id: 5,
    name: "Multi-Surface Cleaner",
    company: "Seventh Generation",
    price: 450,
    unit: "per bottle",
    image: "🧽",
    category: "Household",
    rating: 4.6,
    reviews: 203,
    description: "Plant-based multi-surface cleaner with lemongrass scent",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["EPA Safer Choice", "Plant-based"],
  },
  {
    id: 6,
    name: "Recycled Toilet Paper",
    company: "Seventh Generation",
    price: 320,
    unit: "per 6-pack",
    image: "🧻",
    category: "Household",
    rating: 4.5,
    reviews: 178,
    description: "100% recycled toilet paper, soft and strong",
    inStock: true,
    deliveryTime: "Next day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["100% Recycled", "Forest Stewardship Council"],
  },
  {
    id: 7,
    name: "Dish Soap Concentrate",
    company: "Seventh Generation",
    price: 385,
    unit: "per bottle",
    image: "��",
    category: "Household",
    rating: 4.7,
    reviews: 145,
    description: "Concentrated dish soap with plant-based cleaning power",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["USDA Biobased", "Biodegradable"],
  },

  // Mamaearth Products
  {
    id: 8,
    name: "Vitamin C Face Serum",
    company: "Mamaearth",
    price: 799,
    unit: "per bottle",
    image: "💧",
    category: "Beauty & Personal Care",
    rating: 4.8,
    reviews: 567,
    description: "Natural vitamin C serum for glowing skin",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Natural", "Dermatologically Tested", "Toxin Free"],
  },
  {
    id: 9,
    name: "Onion Hair Oil",
    company: "Mamaearth",
    price: 599,
    unit: "per bottle",
    image: "💆",
    category: "Beauty & Personal Care",
    rating: 4.7,
    reviews: 892,
    description: "Natural onion hair oil for hair growth and strength",
    inStock: true,
    deliveryTime: "Next day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Natural", "No Harmful Chemicals"],
  },
  {
    id: 10,
    name: "Baby Moisturizing Lotion",
    company: "Mamaearth",
    price: 449,
    unit: "per bottle",
    image: "👶",
    category: "Beauty & Personal Care",
    rating: 4.9,
    reviews: 423,
    description: "Gentle, natural moisturizing lotion for babies",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Made Safe", "Pediatrician Approved"],
  },

  // Patagonia Products
  {
    id: 11,
    name: "Recycled Wool Sweater",
    company: "Patagonia",
    price: 8999,
    unit: "per piece",
    image: "🧥",
    category: "Fashion",
    rating: 4.9,
    reviews: 234,
    description: "Warm sweater made from 100% recycled wool",
    inStock: true,
    deliveryTime: "2-3 days delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["Recycled Materials", "Fair Trade", "Climate Neutral"],
  },
  {
    id: 12,
    name: "Organic Cotton T-Shirt",
    company: "Patagonia",
    price: 2999,
    unit: "per piece",
    image: "👕",
    category: "Fashion",
    rating: 4.8,
    reviews: 356,
    description: "Comfortable t-shirt made from organic cotton",
    inStock: true,
    deliveryTime: "2-3 days delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Organic Cotton", "Fair Trade Certified"],
  },

  // Lush Products
  {
    id: 13,
    name: "Shampoo Bar - Honey I Washed My Hair",
    company: "Lush",
    price: 695,
    unit: "per bar",
    image: "🧼",
    category: "Beauty & Personal Care",
    rating: 4.6,
    reviews: 445,
    description: "Plastic-free shampoo bar with honey and toffee scent",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Handmade", "Cruelty Free", "Plastic Free"],
  },
  {
    id: 14,
    name: "Rose Jam Body Gel",
    company: "Lush",
    price: 1250,
    unit: "per bottle",
    image: "🌹",
    category: "Beauty & Personal Care",
    rating: 4.7,
    reviews: 298,
    description: "Luxurious rose-scented shower gel with natural ingredients",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Natural Ingredients", "Cruelty Free"],
  },

  // Beco Products
  {
    id: 15,
    name: "Bamboo Toothbrush Set",
    company: "Beco",
    price: 299,
    unit: "per 4-pack",
    image: "🦷",
    category: "Personal Care",
    rating: 4.5,
    reviews: 156,
    description: "Biodegradable bamboo toothbrushes with soft bristles",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["Biodegradable", "Plastic Free", "Sustainable"],
  },
  {
    id: 16,
    name: "Natural Dish Wash Liquid",
    company: "Beco",
    price: 225,
    unit: "per bottle",
    image: "🍽️",
    category: "Household",
    rating: 4.4,
    reviews: 89,
    description: "Plant-based dish wash liquid that's gentle on hands",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["Plant Based", "Biodegradable"],
  },

  // FabIndia Products
  {
    id: 17,
    name: "Organic Cotton Kurta",
    company: "FabIndia",
    price: 1899,
    unit: "per piece",
    image: "👔",
    category: "Fashion",
    rating: 4.7,
    reviews: 298,
    description: "Handwoven organic cotton kurta in traditional design",
    inStock: true,
    deliveryTime: "2-3 days delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Organic Cotton", "Handloom", "Fair Trade"],
  },
  {
    id: 18,
    name: "Natural Indigo Dupatta",
    company: "FabIndia",
    price: 1299,
    unit: "per piece",
    image: "🧣",
    category: "Fashion",
    rating: 4.6,
    reviews: 167,
    description: "Hand-dyed dupatta with natural indigo",
    inStock: true,
    deliveryTime: "2-3 days delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Natural Dyes", "Handwoven"],
  },

  // The Honest Company Products
  {
    id: 19,
    name: "Baby Diapers - Eco-Friendly",
    company: "The Honest Company",
    price: 1599,
    unit: "per pack",
    image: "👶",
    category: "Baby Care",
    rating: 4.8,
    reviews: 542,
    description: "Plant-based diapers with hypoallergenic materials",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["Hypoallergenic", "Plant Based"],
  },
  {
    id: 20,
    name: "All-Purpose Cleaner",
    company: "The Honest Company",
    price: 425,
    unit: "per bottle",
    image: "🧽",
    category: "Household",
    rating: 4.5,
    reviews: 234,
    description: "Natural all-purpose cleaner safe for families",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["USDA Biobased", "EPA Safer Choice"],
  },

  // Ecover Products
  {
    id: 21,
    name: "Laundry Detergent - Lavender",
    company: "Ecover",
    price: 650,
    unit: "per bottle",
    image: "🧴",
    category: "Household",
    rating: 4.6,
    reviews: 189,
    description: "Concentrated laundry detergent with natural lavender",
    inStock: true,
    deliveryTime: "Next day delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["EU Ecolabel", "Biodegradable"],
  },

  // Allbirds Products
  {
    id: 22,
    name: "Tree Runners - Sustainable Sneakers",
    company: "Allbirds",
    price: 9500,
    unit: "per pair",
    image: "👟",
    category: "Fashion",
    rating: 4.7,
    reviews: 456,
    description: "Comfortable sneakers made from eucalyptus tree fiber",
    inStock: true,
    deliveryTime: "3-5 days delivery",
    organic: false,
    ecoFriendly: true,
    certifications: ["Carbon Neutral", "FSC Certified"],
  },

  // The Body Shop Products
  {
    id: 23,
    name: "Tea Tree Oil",
    company: "The Body Shop",
    price: 995,
    unit: "per bottle",
    image: "🌿",
    category: "Beauty & Personal Care",
    rating: 4.6,
    reviews: 678,
    description: "Pure tea tree oil for natural skincare",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Cruelty Free", "Fair Trade"],
  },
  {
    id: 24,
    name: "Shea Butter Hand Cream",
    company: "The Body Shop",
    price: 695,
    unit: "per tube",
    image: "🧴",
    category: "Beauty & Personal Care",
    rating: 4.8,
    reviews: 345,
    description: "Nourishing hand cream with community fair trade shea butter",
    inStock: true,
    deliveryTime: "Same day delivery",
    organic: true,
    ecoFriendly: true,
    certifications: ["Fair Trade", "Natural Ingredients"],
  },
];

export const farmers: Farmer[] = [
  {
    id: 1,
    name: "Green Valley Farm",
    owner: "Sarah Johnson",
    location: "Maharashtra, India",
    image: "👩‍🌾",
    specialties: ["Organic Fruits", "Heirloom Vegetables"],
    certifications: ["USDA Organic", "Fair Trade"],
    experience: "15 years",
    description:
      "Family-owned farm specializing in sustainable growing practices and heirloom varieties.",
    customers: 450,
    products: 28,
  },
  {
    id: 2,
    name: "Sunshine Organics",
    owner: "Raj Patel",
    location: "Punjab, India",
    image: "👨‍🌾",
    specialties: ["Leafy Greens", "Herbs"],
    certifications: ["USDA Organic", "Certified Naturally Grown"],
    experience: "12 years",
    description:
      "Dedicated to providing the freshest greens using regenerative farming methods.",
    customers: 320,
    products: 15,
  },
  {
    id: 3,
    name: "Heritage Gardens",
    owner: "Priya Sharma",
    location: "Karnataka, India",
    image: "👩‍🌾",
    specialties: ["Heirloom Tomatoes", "Seasonal Vegetables"],
    certifications: ["Biodynamic", "Organic India"],
    experience: "20 years",
    description:
      "Preserving heirloom varieties and promoting biodiversity through sustainable farming.",
    customers: 680,
    products: 35,
  },
  {
    id: 4,
    name: "Happy Hen Farm",
    owner: "Vikram Singh",
    location: "Haryana, India",
    image: "👨‍🌾",
    specialties: ["Free-Range Eggs", "Organic Dairy"],
    certifications: ["Certified Humane", "Pasture Raised"],
    experience: "8 years",
    description:
      "Committed to ethical animal husbandry and producing the highest quality dairy products.",
    customers: 290,
    products: 8,
  },
];

export const deliveryZones: DeliveryZone[] = [
  {
    zone: "Same Day Delivery",
    areas: "Mumbai, Delhi, Bangalore, Hyderabad",
    cutoff: "12:00 PM",
    fee: "Free over ₹500",
    icon: "🏃‍♂️",
  },
  {
    zone: "Next Day Delivery",
    areas: "Pune, Chennai, Kolkata, Ahmedabad",
    cutoff: "6:00 PM",
    fee: "Free over ₹750",
    icon: "🚚",
  },
  {
    zone: "2-Day Delivery",
    areas: "Tier 2 Cities, Rural Areas",
    cutoff: "11:59 PM",
    fee: "₹99 flat rate",
    icon: "📦",
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 1,
    name: "Eco Essentials",
    description: "Perfect for individuals starting their eco-friendly journey",
    price: 999,
    deliveryFrequency: "Monthly",
    features: [
      "5-7 eco-friendly products",
      "Free delivery",
      "Educational materials",
      "Beginner-friendly products",
    ],
  },
  {
    id: 2,
    name: "Green Family",
    description: "Ideal for families committed to sustainable living",
    price: 1999,
    deliveryFrequency: "Monthly",
    popular: true,
    features: [
      "12-15 eco-friendly products",
      "Free delivery",
      "Family-size products",
      "Exclusive discounts",
      "Priority customer support",
    ],
  },
  {
    id: 3,
    name: "Planet Protector",
    description: "For eco-warriors who want maximum impact",
    price: 2999,
    deliveryFrequency: "Monthly",
    features: [
      "20+ premium eco products",
      "Free express delivery",
      "Early access to new products",
      "Bulk buying options",
      "Personalized recommendations",
      "Carbon footprint report",
    ],
  },
];

export const categories = [
  { name: "Fresh Fruits", icon: "🍎" },
  { name: "Vegetables", icon: "🥕" },
  { name: "Dairy & Eggs", icon: "🥛" },
  { name: "Household", icon: "🏠" },
  { name: "Beauty & Personal Care", icon: "🧴" },
  { name: "Fashion", icon: "👕" },
  { name: "Personal Care", icon: "🦷" },
  { name: "Baby Care", icon: "🍼" },
];
